import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'
import { SearchIcon, MicrophoneIcon } from "@heroicons/react/solid"
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Google App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Body  */}
      <form className='flex flex-col items-center mt-40'>
        <Image
          objectFit='cover'
          width={300}
          height={100}
          src={"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png"} />
        <div className='flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200  hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center  sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 text-gray-500 mr-3 className="btn"' />
          <input type="text" className='flex-grow focus:outline-none '></input>
          <MicrophoneIcon className='h-5' />
        </div>
        <div className='flex flex-col mt-3 sm:flex-row w-[50%] space-y-2 mt-8 sm: space-y-0 sm: space-x-4 justify-center'><button className="btn">Buscar con google </button>
          <button className="btn">Voy a tener suerte </button></div>

      </form>

      {/* footer */}
      <Footer />
    </div>
  )
}
